name: Java CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd backend
        mvn clean install -Dspring.main.web-application-type=none -DskipTests
        # mvn clean install -DskipTests

    - name: Run tests
      run: |
        cd backend
        mvn test

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: success()

    steps:
    - name: Check out the code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Build with Maven
      run: |
        cd backend
        mvn clean install -DskipTests

    - name: Deploy to production (exemplo)
      run: |
        echo "Deploying to production server..."
        # Aqui você pode adicionar o comando para realizar o deploy, por exemplo:
        # scp backend/target/your-app.war user@server:/path/to/deploy
